### ISSUE TITLE
Create Leap Subclasses of the Abstract Interface Classes

### ISSUE THREAD

**Issue by michaelschiff** [hbradlow/pyGesture#10]
subclass the files in interfaces to allow for generalized access to the data provided by the leap motion device

**Comment by hbradlow** [comment]
Closed by d0a031678b6a0b30e1ed1ff41b699ee5d9503ef0

**Comment by michaelschiff** [comment]
Im not sure this was the right way too do this.... I feel like too many implementation details are above the abstraction level.  You can see how specific collect.py is to the Leap still, and this is where it should be most general.  I think that the overall approach is okay but that we should refactor things to expose less detail at higher levels.
