### ISSUE TITLE
Move to numpy array

### ISSUE THREAD

**Issue by hbradlow** [hbradlow/pyGesture#3]
Convert the code to use numpy arrays instead of Leap Vectors

**Comment by syadlowsky** [comment]
Is this related to saving / pickling?

**Comment by michaelschiff** [comment]
The saving/pickling thing is issue #5. I think this one is just to switch from leap's vectors to numpy arrays since they are really fast and let you perform a bunch of cool operations on multidimensional arrays.

**Comment by hbradlow** [comment]
I just wrote a bunch of functions that are already implemented by numpy. They should be replaced

See [utils.py](https://github.com/hbradlow/pyGesture/blob/master/utils.py)

**Comment by hbradlow** [comment]
Closed by c4d08e2badef2f8555e4f1a24daba3ca15ee88a1
